FROM golang:1.17.7-alpine3.15 as builder

WORKDIR /concourse/time-resource
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . /concourse/time-resource
ENV CGO_ENABLED 0
RUN go build -o /assets/out github.com/concourse/time-resource/out
RUN go build -o /assets/in github.com/concourse/time-resource/in
RUN go build -o /assets/check github.com/concourse/time-resource/check

FROM alpine:latest AS resource
RUN apk update && apk upgrade
RUN apk add --update bash tzdata
COPY --from=builder /assets /opt/resource

FROM resource