FROM golang:1.17.7-alpine3.15 as builder
RUN apk add git
ENV REGISTRY_IMAGE_COMMIT=b4a72559ebcc1c4ea703abb410aa1fc19180957f


RUN git clone https://github.com/moczix/registry-image-resource.git /src/registry-image-resource
WORKDIR /src/registry-image-resource
RUN git checkout $REGISTRY_IMAGE_COMMIT
ENV CGO_ENABLED 0
RUN go get -d ./...
RUN go build -o /assets/in ./cmd/in
RUN go build -o /assets/out ./cmd/out
RUN go build -o /assets/check ./cmd/check

FROM alpine:edge AS resource
RUN apk add --no-cache bash tzdata ca-certificates unzip zip gzip tar
COPY --from=builder assets/ /opt/resource/
RUN chmod +x /opt/resource/*

FROM resource
WORKDIR /go/registry-image-resource

