FROM golang:1.17.0-alpine3.14 as builder
RUN apk add git
ENV REGISTRY_IMAGE_COMMIT=2113c3cf8fda284ba0670230a4ea996b98a5a9b4


RUN git clone https://github.com/moczix/registry-image-resource.git /src/registry-image-resource
WORKDIR /src/registry-image-resource
RUN git checkout $REGISTRY_IMAGE_COMMIT
ENV CGO_ENABLED 0
RUN go get -d ./...
RUN go build -o /assets/in ./cmd/in
RUN go build -o /assets/out ./cmd/out
RUN go build -o /assets/check ./cmd/check

FROM alpine:edge AS resource
RUN apk add --no-cache bash tzdata ca-certificates unzip zip gzip tar
COPY --from=builder assets/ /opt/resource/
RUN chmod +x /opt/resource/*

FROM resource
WORKDIR /go/registry-image-resource

