FROM golang:1.17.7-alpine3.15 as builder
RUN apk add git
ENV TIME_RESOURCE_COMMIT=fe48102cf21de72ded9c846c8f813c117894d123


RUN git clone https://github.com/concourse/time-resource.git /src/time-resource
WORKDIR /src/time-resource
RUN git checkout $TIME_RESOURCE_COMMIT


WORKDIR /src/time-resource
ENV CGO_ENABLED 0
RUN go build -o /assets/out github.com/concourse/time-resource/out
RUN go build -o /assets/in github.com/concourse/time-resource/in
RUN go build -o /assets/check github.com/concourse/time-resource/check

FROM alpine:latest AS resource
RUN apk update && apk upgrade
RUN apk add --update bash tzdata
COPY --from=builder /assets /opt/resource

FROM resource